# Generated by Django 5.1.4 on 2025-02-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_member_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('care', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
