# Generated by Django 5.1.4 on 2025-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_plant'),
    ]

    operations = [
    ]
