# Generated by Django 5.1.7 on 2025-03-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20250225_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_photos/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
