# Generated by Django 5.1.7 on 2025-03-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_event_plant_photo_alter_plant_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
