# Generated by Django 5.1.7 on 2025-03-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_plant_location_alter_plant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
