# Generated by Django 5.1.7 on 2025-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_plant_location_alter_plant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='care',
            new_name='care_instructions',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='type',
            new_name='plant_type',
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
