# Generated by Django 5.1.7 on 2025-03-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_care_plant_care_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_photos/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
