# Generated by Django 5.1.7 on 2025-03-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_plant_type_plant_type_alter_plant_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='type',
            new_name='plant_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='photo',
        ),
    ]
