# Generated by Django 5.1.7 on 2025-03-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_type_plant_plant_type_remove_plant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_photos/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
