# Generated by Django 5.1.7 on 2025-04-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_plant_photo_alter_plant_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
